[package]
name = "mpdfin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
# chrono = "0.4"
toml = "0.5"
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
souvlaki = "0.5"
dirs = "4"
async-trait = "0.1"
strum = { version = "0.24", features = ["derive"] }
libmpv = "2.0"

jellyfin-client = { git = "https://github.com/ilyazzz/jellyfin-client-rs" }