[package]
name = "mpdfin-mediakeys"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
interoptopus = "0.14.18"
souvlaki = "0.6.1"

[dev-dependencies]
interoptopus_backend_csharp = "0.14.18"
